# Generated by Django 5.0.1 on 2024-02-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='TickerData',
        ),
    ]
