# Generated by Django 5.0.1 on 2024-02-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('ticker', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('start_open', models.FloatField()),
                ('start_close', models.FloatField()),
                ('start_high', models.FloatField()),
                ('start_low', models.FloatField()),
                ('volume', models.FloatField()),
            ],
        ),
    ]