# Generated by Django 5.0.1 on 2024-02-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_classname_tickerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdata',
            name='start_date',
            field=models.BigIntegerField(),
        ),
    ]
