# Generated by Django 5.0.1 on 2024-02-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tickerdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdata',
            name='date',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='ticker',
            field=models.CharField(max_length=4),
        ),
    ]
