# Generated by Django 5.0.4 on 2024-04-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tickerdata_date_alter_tickerdata_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendData',
            fields=[
                ('ticker', models.CharField(default='TICK', max_length=4, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Company Name', max_length=100)),
                ('start_date', models.DateField(default='1900-01-01')),
                ('end_date', models.DateField(default='1900-01-01')),
                ('dividend_yield_ratio', models.FloatField(default=0.0)),
                ('start_open', models.FloatField(default=0.0)),
                ('start_close', models.FloatField(default=0.0)),
                ('start_high', models.FloatField(default=0.0)),
                ('start_low', models.FloatField(default=0.0)),
                ('end_open', models.FloatField(default=0.0)),
                ('end_close', models.FloatField(default=0.0)),
                ('end_high', models.FloatField(default=0.0)),
                ('end_low', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('ticker', models.CharField(default='TICK', max_length=4, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='Company Name', max_length=100)),
                ('start_date', models.DateField(default='1900-01-01')),
                ('end_date', models.DateField(default='1900-01-01')),
                ('book_value', models.FloatField(default=0.0)),
                ('book_to_share_value', models.FloatField(default=0.0)),
                ('earnings_per_share', models.FloatField(default=0.0)),
                ('debt_ratio', models.FloatField(default=0.0)),
                ('current_ratio', models.FloatField(default=0.0)),
                ('start_open', models.FloatField(default=0.0)),
                ('start_close', models.FloatField(default=0.0)),
                ('start_high', models.FloatField(default=0.0)),
                ('end_open', models.FloatField(default=0.0)),
                ('end_close', models.FloatField(default=0.0)),
                ('end_high', models.FloatField(default=0.0)),
                ('end_low', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tickerdata',
            name='date',
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='book_to_share_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='book_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=100),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='current_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='debt_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='earnings_per_share',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='end_close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='end_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='end_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='end_low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tickerdata',
            name='end_open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='start_close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='start_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='start_high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='start_low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='start_open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='ticker',
            field=models.CharField(default='TICK', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
