# Generated by Django 5.0.4 on 2024-04-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_companyticker_remove_tickerdata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdata',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='ticker',
            field=models.CharField(default='TICK', max_length=4),
        ),
    ]
