# Generated by Django 5.0.4 on 2024-04-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_companyticker_tickerdata_book_to_share_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerdata',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='start_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
